var annotated_dup =
[
    [ "controllers", "namespacecontrollers.html", [
      [ "BangBang", "classcontrollers_1_1_bang_bang.html", "classcontrollers_1_1_bang_bang" ],
      [ "DoubleSetpoint", "classcontrollers_1_1_double_setpoint.html", "classcontrollers_1_1_double_setpoint" ],
      [ "PID", "classcontrollers_1_1_p_i_d.html", "classcontrollers_1_1_p_i_d" ],
      [ "PID_Discrete", "classcontrollers_1_1_p_i_d___discrete.html", "classcontrollers_1_1_p_i_d___discrete" ],
      [ "ZTransformStatic", "classcontrollers_1_1_z_transform_static.html", "classcontrollers_1_1_z_transform_static" ],
      [ "ZTransform", "classcontrollers_1_1_z_transform.html", "classcontrollers_1_1_z_transform" ]
    ] ],
    [ "AeroCoefficients", "struct_aero_coefficients.html", "struct_aero_coefficients" ],
    [ "AHRSParams", "struct_a_h_r_s_params.html", "struct_a_h_r_s_params" ],
    [ "Ammo", "class_ammo.html", "class_ammo" ],
    [ "Cargo", "class_cargo.html", "class_cargo" ],
    [ "Controller", "class_controller.html", "class_controller" ],
    [ "ControllerTest", "class_controller_test.html", "class_controller_test" ],
    [ "ControlSurfaces", "class_control_surfaces.html", "class_control_surfaces" ],
    [ "Drive", "struct_drive.html", "struct_drive" ],
    [ "EKFScalers", "struct_e_k_f_scalers.html", "struct_e_k_f_scalers" ],
    [ "Hinge", "class_hinge.html", "class_hinge" ],
    [ "Jet", "class_jet.html", "class_jet" ],
    [ "Load", "class_load.html", "class_load" ],
    [ "Logger", "class_logger.html", "class_logger" ],
    [ "ODE", "class_o_d_e.html", "class_o_d_e" ],
    [ "ODE_Euler", "class_o_d_e___euler.html", "class_o_d_e___euler" ],
    [ "ODE_Heun", "class_o_d_e___heun.html", "class_o_d_e___heun" ],
    [ "ODE_PC2", "class_o_d_e___p_c2.html", "class_o_d_e___p_c2" ],
    [ "ODE_PC4", "class_o_d_e___p_c4.html", "class_o_d_e___p_c4" ],
    [ "ODE_RK4", "class_o_d_e___r_k4.html", "class_o_d_e___r_k4" ],
    [ "ODETest", "class_o_d_e_test.html", "class_o_d_e_test" ],
    [ "Rotor", "struct_rotor.html", "struct_rotor" ],
    [ "SensorParams", "struct_sensor_params.html", "struct_sensor_params" ],
    [ "TimedLoop", "class_timed_loop.html", "class_timed_loop" ],
    [ "UAVparams", "struct_u_a_vparams.html", "struct_u_a_vparams" ]
];